### ISSUE TITLE
[Bug] Going on your orders gives errors

### ISSUE THREAD

**Issue by gsc2001** [Domino-Developers/Larena#31]

**Comment by tichnas** [comment]
Which errors?

**Comment by gsc2001** [comment]
![image](https://user-images.githubusercontent.com/56212978/104842822-4f8bfd80-58ed-11eb-888f-81838482bea4.png)
![image](https://user-images.githubusercontent.com/56212978/104842835-5a469280-58ed-11eb-9a7a-ee5a96139027.png)

**Comment by tichnas** [comment]
Oh, sry
